"""added isavailable attribute

Revision ID: 8dce3f7f6ba7
Revises: ce0e39acb139
Create Date: 2023-05-10 11:37:37.758515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dce3f7f6ba7'
down_revision = 'ce0e39acb139'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_available', sa.String(), server_default='True', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_column('is_available')

    # ### end Alembic commands ###
